### ISSUE TITLE
stable_to_next_ha missing ha-next.yaml and manifest commands to deploy ha-next.yaml

### ISSUE THREAD

**Issue by ajkavanagh** [openstack-charmers/openstack-mojo-specs#114]
stable_to_next_ha (currently) misses the memcached charm.  It is referred to in collect-next-ha, but refers to cs:~openstack-charmers/memcached which doesn't exist (it's cs:memcached)

Also, the ha-next.yaml does include the memcached charm references and the relation to nova-cloud-controller, but the manifest for stable_to_next_ha (for each distro version) doesn't appear to have a step to install it.

Currently testing various combinations to see what is the most effective fix.

**Comment by ryan-beisner** [comment]
Moved to: https://bugs.launchpad.net/openstack-mojo-specs/+bug/1836946
